apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-serviceb
  labels:
    app: serviceb-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb-poc
  template:
    metadata:
      labels:
        app: serviceb-poc
    spec:
      containers:
        - name: serviceb-poc
          image: sriharipriya/serviceb-poc:${{ github.run_number }}

          ports: 
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: serviceb-poc-loadbalancer-service
  labels:
    app: serviceb-poc
spec:
  type: LoadBalancer
  selector:
    app: serviceb-poc
  ports:
    - port: 8081
      targetPort: 8081
